

REG_LEN              = 64
REG_EEPROM_BUFF_LEN  = 16


REG_WD_INTERVAL     = 0
REG_SLEEP_TIME      = REG_WD_INTERVAL + 4
REG_WD_OFF_TIME     = REG_SLEEP_TIME + 4
REG_LOAD_SW         = REG_WD_OFF_TIME + 4
REG_EEPROM_STATE    = REG_LOAD_SW +1
REG_EEPROM_ADDR     = REG_EEPROM_STATE + 1
REG_SLEEP_STATE     = REG_EEPROM_ADDR + 1
REG_CLR_WD          = REG_SLEEP_STATE + 1
REG_RESERVED_1      = REG_CLR_WD + 1
REG_EEPROM_BUFF     = REG_RESERVED_1 + 15

EEPROM_IDLE         = 0
EEPROM_WR_BUFF      = 1
EEPROM_RD_BUFF      = 2
EEPROM_READY        = 3

SLEEP_INACTIVE = 0
SLEEP_ACTIVATED = 1
SLEEP_ZZZZZ = 2