CMD_WD_UNDEF         = 0x00
CMD_SET_WD_INTERVAL  = 0x01
CMD_GET_WD_INTERVAL  = 0x02
CMD_SET_SLEEP_TIME   = 0x03
CMD_GET_SLEEP_TIME   = 0x04
CMD_CLEAR_WATCHDOG   = 0x05
CMD_SWITCH_OFF       = 0x06
CMD_SET_EEPROM_ADDR  = 0x07
CMD_EEPROM_LOAD      = 0x08
CMD_EEPROM_SAVE      = 0x09
CMD_POWER_OFF_0      = 0x0A
CMD_RESERVED_1       = 0x0B
CMD_EXT_RESET        = 0x0C
CMD_EEPROM_READ      = 0x0D
CMD_EEPROM_WRITE     = 0x0E
CMD_GET_RESTARTS     = 0x0F
CMD_NBR_OF           = 14


REG_LEN              = 64
REG_EEPROM_BUFF_LEN  = 16
REG_NBR_LOAD_SW      = 2


REG_WD_INTERVAL     = 0
REG_SLEEP_TIME      = REG_WD_INTERVAL + 4
REG_LOAD_SW         = REG_SLEEP_TIME + 4
REG_EEPROM_STATE    = REG_LOAD_SW + REG_NBR_LOAD_SW
REG_EEPROM_ADDR     = REG_EEPROM_STATE + 1
REG_RESERVED_1      = REG_EEPROM_ADDR + 1
REG_EEPROM_BUFF     = REG_RESERVED_1 + 4

EEPROM_IDLE         = 0
EEPROM_WR_BUFF      = 1
EEPROM_RD_BUFF      = 2
EEPROM_READY        = 3